version: '3'

services:
  db:
    image: postgres:9.6
    environment: &postgres_env
      POSTGRES_DB: app_dev_1
      POSTGRES_USER: test
      POSTGRES_PASSWORD: test
    ports:
      - 5433:5432
    volumes:
      - db_data:/var/lib/postgresql/data

  rails_dev_1:
    build: .
    command: dev
    image: rails_fciencias:1.0
    ports:
      - 3001:3000
    volumes:
      - ./app:/usr/src/app
      - ./bin:/usr/src/scripts
    environment:
      <<: *postgres_env
    entrypoint: /usr/src/scripts/docker-entrypoint.sh
    links:
      - db

volumes:
  db_data:
    driver: local
